/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClassGroup {
  'id' : string,
  'joinCode' : string,
  'name' : string,
  'createdAt' : Time,
  'memberNames' : Array<string>,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'name' : string,
  'grade' : number,
}
export interface PlayerProfile {
  'xp' : bigint,
  'name' : string,
  'badges' : Array<string>,
  'streakDays' : bigint,
  'weakTopics' : Array<string>,
  'lastPlayedEpoch' : Time,
  'grade' : number,
}
export interface PublicStats {
  'activeUsers' : bigint,
  'leaderboard' : Array<LeaderboardEntry>,
  'totalVisits' : bigint,
}
export interface StudentRegistryEntry {
  'xp' : bigint,
  'name' : string,
  'streakDays' : bigint,
  'grade' : number,
  'badgeCount' : bigint,
  'lastActive' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'createClass' : ActorMethod<[string, string], string>,
  'createOrUpdateProfile' : ActorMethod<[string, number], undefined>,
  'getActiveUsers' : ActorMethod<[], bigint>,
  'getAllClasses' : ActorMethod<[], Array<ClassGroup>>,
  'getAllStudentProfiles' : ActorMethod<[], Array<StudentRegistryEntry>>,
  'getClassByCode' : ActorMethod<[string], [] | [ClassGroup]>,
  'getProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getPublicStats' : ActorMethod<[], PublicStats>,
  'getTopLeaderboardEntries' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTotalVisits' : ActorMethod<[], bigint>,
  'getUnlockedLevels' : ActorMethod<[string], Array<bigint>>,
  'getWeeklyTopPlayers' : ActorMethod<[], Array<StudentRegistryEntry>>,
  'heartbeat' : ActorMethod<[string], undefined>,
  'joinClass' : ActorMethod<[string, string], boolean>,
  'recordGameSession' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, string],
    undefined
  >,
  'removeStudentFromClass' : ActorMethod<[string, string], undefined>,
  'resetProgress' : ActorMethod<[], undefined>,
  'submitLeaderboardEntry' : ActorMethod<
    [string, number, bigint, bigint, bigint],
    undefined
  >,
  'trackVisit' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];