/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'streakDays' : IDL.Nat,
  'weakTopics' : IDL.Vec(IDL.Text),
  'lastPlayedEpoch' : Time,
  'grade' : IDL.Nat8,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'name' : IDL.Text,
  'grade' : IDL.Nat8,
});

export const idlService = IDL.Service({
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Nat8], [], []),
  'getProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getTopLeaderboardEntries' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTotalVisits' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnlockedLevels' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'recordGameSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'resetProgress' : IDL.Func([], [], []),
  'trackVisit' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'streakDays' : IDL.Nat,
    'weakTopics' : IDL.Vec(IDL.Text),
    'lastPlayedEpoch' : Time,
    'grade' : IDL.Nat8,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'grade' : IDL.Nat8,
  });
  
  return IDL.Service({
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Nat8], [], []),
    'getProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getTopLeaderboardEntries' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTotalVisits' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnlockedLevels' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'recordGameSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'resetProgress' : IDL.Func([], [], []),
    'trackVisit' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };